"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.order import Order
globals()['Order'] = Order
from kalshi.model.user_order_decrease_response import UserOrderDecreaseResponse


class TestUserOrderDecreaseResponse(unittest.TestCase):
    """UserOrderDecreaseResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserOrderDecreaseResponse(self):
        """Test UserOrderDecreaseResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserOrderDecreaseResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
