"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.user_trade_list import UserTradeList
globals()['UserTradeList'] = UserTradeList
from kalshi.model.user_trades_get_response import UserTradesGetResponse


class TestUserTradesGetResponse(unittest.TestCase):
    """UserTradesGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserTradesGetResponse(self):
        """Test UserTradesGetResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserTradesGetResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
