"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.change_subscription_request import ChangeSubscriptionRequest


class TestChangeSubscriptionRequest(unittest.TestCase):
    """ChangeSubscriptionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChangeSubscriptionRequest(self):
        """Test ChangeSubscriptionRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChangeSubscriptionRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
