"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.order import Order
globals()['Order'] = Order
from openapi_client.model.order_list import OrderList


class TestOrderList(unittest.TestCase):
    """OrderList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderList(self):
        """Test OrderList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrderList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
