"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.market_api import MarketApi  # noqa: E501


class TestMarketApi(unittest.TestCase):
    """MarketApi unit test stubs"""

    def setUp(self):
        self.api = MarketApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_market(self):
        """Test case for get_market

        GetMarket  # noqa: E501
        """
        pass

    def test_get_market_history(self):
        """Test case for get_market_history

        GetMarketHistory  # noqa: E501
        """
        pass

    def test_get_market_order_book(self):
        """Test case for get_market_order_book

        GetMarketOrderBook  # noqa: E501
        """
        pass

    def test_get_markets(self):
        """Test case for get_markets

        GetMarkets  # noqa: E501
        """
        pass

    def test_get_markets_cached(self):
        """Test case for get_markets_cached

        GetMarketsCached  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
