"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.account_history_entry import AccountHistoryEntry
globals()['AccountHistoryEntry'] = AccountHistoryEntry
from openapi_client.model.user_get_account_history_response import UserGetAccountHistoryResponse


class TestUserGetAccountHistoryResponse(unittest.TestCase):
    """UserGetAccountHistoryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserGetAccountHistoryResponse(self):
        """Test UserGetAccountHistoryResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserGetAccountHistoryResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
