"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.banking_api import BankingApi  # noqa: E501


class TestBankingApi(unittest.TestCase):
    """BankingApi unit test stubs"""

    def setUp(self):
        self.api = BankingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_user_deposits(self):
        """Test case for get_user_deposits

        GetUserDeposits  # noqa: E501
        """
        pass

    def test_get_user_withdrawals(self):
        """Test case for get_user_withdrawals

        GetUserWithdrawals  # noqa: E501
        """
        pass

    def test_user_create_plaid_link_token(self):
        """Test case for user_create_plaid_link_token

        UserCreatePlaidLinkToken  # noqa: E501
        """
        pass

    def test_user_link_bank_accounts(self):
        """Test case for user_link_bank_accounts

        UserLinkBankAccounts  # noqa: E501
        """
        pass

    def test_user_list_ledgerx_bank_accounts(self):
        """Test case for user_list_ledgerx_bank_accounts

        UserListLedgerxBankAccounts  # noqa: E501
        """
        pass

    def test_user_request_deposit(self):
        """Test case for user_request_deposit

        UserRequestDeposit  # noqa: E501
        """
        pass

    def test_user_request_withdrawal(self):
        """Test case for user_request_withdrawal

        UserRequestWithdrawal  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
