"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.ranged_market import RangedMarket
globals()['RangedMarket'] = RangedMarket
from kalshi.model.get_ranged_markets_response import GetRangedMarketsResponse


class TestGetRangedMarketsResponse(unittest.TestCase):
    """GetRangedMarketsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetRangedMarketsResponse(self):
        """Test GetRangedMarketsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetRangedMarketsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
