"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.reset_password_request import ResetPasswordRequest


class TestResetPasswordRequest(unittest.TestCase):
    """ResetPasswordRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResetPasswordRequest(self):
        """Test ResetPasswordRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ResetPasswordRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
