"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.order_book import OrderBook
globals()['OrderBook'] = OrderBook
from kalshi.model.get_market_order_book_response import GetMarketOrderBookResponse


class TestGetMarketOrderBookResponse(unittest.TestCase):
    """GetMarketOrderBookResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetMarketOrderBookResponse(self):
        """Test GetMarketOrderBookResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetMarketOrderBookResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
