"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.withdrawal import Withdrawal
globals()['Withdrawal'] = Withdrawal
from openapi_client.model.get_user_withdrawals_response import GetUserWithdrawalsResponse


class TestGetUserWithdrawalsResponse(unittest.TestCase):
    """GetUserWithdrawalsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetUserWithdrawalsResponse(self):
        """Test GetUserWithdrawalsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetUserWithdrawalsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
