"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.send_sign_up_link_request import SendSignUpLinkRequest


class TestSendSignUpLinkRequest(unittest.TestCase):
    """SendSignUpLinkRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendSignUpLinkRequest(self):
        """Test SendSignUpLinkRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SendSignUpLinkRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
