"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.bank_account_details import BankAccountDetails
globals()['BankAccountDetails'] = BankAccountDetails
from kalshi.model.user_list_ledgerx_bank_accounts_response import UserListLedgerxBankAccountsResponse


class TestUserListLedgerxBankAccountsResponse(unittest.TestCase):
    """UserListLedgerxBankAccountsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserListLedgerxBankAccountsResponse(self):
        """Test UserListLedgerxBankAccountsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserListLedgerxBankAccountsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
