# flake8: noqa

"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from kalshi.api_client import ApiClient

# import Configuration
from kalshi.configuration import Configuration

# import exceptions
from kalshi.exceptions import OpenApiException
from kalshi.exceptions import ApiAttributeError
from kalshi.exceptions import ApiTypeError
from kalshi.exceptions import ApiValueError
from kalshi.exceptions import ApiKeyError
from kalshi.exceptions import ApiException
