"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.bank_account_details import BankAccountDetails


class TestBankAccountDetails(unittest.TestCase):
    """BankAccountDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBankAccountDetails(self):
        """Test BankAccountDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BankAccountDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
