"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.portfolio_api import PortfolioApi  # noqa: E501


class TestPortfolioApi(unittest.TestCase):
    """PortfolioApi unit test stubs"""

    def setUp(self):
        self.api = PortfolioApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_user_get_portfolio_history(self):
        """Test case for user_get_portfolio_history

        UserGetPortfolioHistory  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
