"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.ranged_markets_api import RangedMarketsApi  # noqa: E501


class TestRangedMarketsApi(unittest.TestCase):
    """RangedMarketsApi unit test stubs"""

    def setUp(self):
        self.api = RangedMarketsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_ranged_market_by_ticker(self):
        """Test case for get_ranged_market_by_ticker

        GetRangedMarketByTicker  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
