"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.deposit_history import DepositHistory
from kalshi.model.order_history import OrderHistory
from kalshi.model.settlement_history import SettlementHistory
from kalshi.model.trade_history import TradeHistory
from kalshi.model.withdrawal_history import WithdrawalHistory
globals()['DepositHistory'] = DepositHistory
globals()['OrderHistory'] = OrderHistory
globals()['SettlementHistory'] = SettlementHistory
globals()['TradeHistory'] = TradeHistory
globals()['WithdrawalHistory'] = WithdrawalHistory
from kalshi.model.account_history_entry_data import AccountHistoryEntryData


class TestAccountHistoryEntryData(unittest.TestCase):
    """AccountHistoryEntryData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountHistoryEntryData(self):
        """Test AccountHistoryEntryData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountHistoryEntryData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
