"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.ranged_market import RangedMarket
globals()['RangedMarket'] = RangedMarket
from openapi_client.model.get_ranged_market_response import GetRangedMarketResponse


class TestGetRangedMarketResponse(unittest.TestCase):
    """GetRangedMarketResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetRangedMarketResponse(self):
        """Test GetRangedMarketResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetRangedMarketResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
