"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.deposit_history import DepositHistory


class TestDepositHistory(unittest.TestCase):
    """DepositHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDepositHistory(self):
        """Test DepositHistory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DepositHistory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
