"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.public_trade_list import PublicTradeList
globals()['PublicTradeList'] = PublicTradeList
from kalshi.model.trades_get_response import TradesGetResponse


class TestTradesGetResponse(unittest.TestCase):
    """TradesGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTradesGetResponse(self):
        """Test TradesGetResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TradesGetResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
