"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.login_response import LoginResponse


class TestLoginResponse(unittest.TestCase):
    """LoginResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoginResponse(self):
        """Test LoginResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LoginResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
