"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.ranged_market_api import RangedMarketApi  # noqa: E501


class TestRangedMarketApi(unittest.TestCase):
    """RangedMarketApi unit test stubs"""

    def setUp(self):
        self.api = RangedMarketApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_ranged_market(self):
        """Test case for get_ranged_market

        GetRangedMarket  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
