"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.user_api import UserApi  # noqa: E501


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_user_add_watchlist(self):
        """Test case for user_add_watchlist

        UserAddWatchlist  # noqa: E501
        """
        pass

    def test_user_change_password(self):
        """Test case for user_change_password

        UserChangePassword  # noqa: E501
        """
        pass

    def test_user_get_balance(self):
        """Test case for user_get_balance

        UserGetBalance  # noqa: E501
        """
        pass

    def test_user_get_market_position(self):
        """Test case for user_get_market_position

        UserGetMarketPosition  # noqa: E501
        """
        pass

    def test_user_get_market_positions(self):
        """Test case for user_get_market_positions

        UserGetMarketPositions  # noqa: E501
        """
        pass

    def test_user_get_profile(self):
        """Test case for user_get_profile

        UserGetProfile  # noqa: E501
        """
        pass

    def test_user_get_watchlist(self):
        """Test case for user_get_watchlist

        UserGetWatchlist  # noqa: E501
        """
        pass

    def test_user_order_cancel(self):
        """Test case for user_order_cancel

        UserOrderCancel  # noqa: E501
        """
        pass

    def test_user_order_create(self):
        """Test case for user_order_create

        UserOrderCreate  # noqa: E501
        """
        pass

    def test_user_order_decrease(self):
        """Test case for user_order_decrease

        UserOrderDecrease  # noqa: E501
        """
        pass

    def test_user_orders_get(self):
        """Test case for user_orders_get

        UserOrdersGet  # noqa: E501
        """
        pass

    def test_user_remove_watchlist(self):
        """Test case for user_remove_watchlist

        UserRemoveWatchlist  # noqa: E501
        """
        pass

    def test_user_trades_get(self):
        """Test case for user_trades_get

        UserTradesGet  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
