"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.market_stats_point import MarketStatsPoint
globals()['MarketStatsPoint'] = MarketStatsPoint
from kalshi.model.get_market_history_response import GetMarketHistoryResponse


class TestGetMarketHistoryResponse(unittest.TestCase):
    """GetMarketHistoryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetMarketHistoryResponse(self):
        """Test GetMarketHistoryResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetMarketHistoryResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
