"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kalshi
from kalshi.model.market_position import MarketPosition


class TestMarketPosition(unittest.TestCase):
    """MarketPosition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMarketPosition(self):
        """Test MarketPosition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MarketPosition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
