"""
    Kalshi API.

    This documentation describes Kalshi's rest API for market makers  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.notification import Notification
globals()['Notification'] = Notification
from openapi_client.model.notification_list import NotificationList


class TestNotificationList(unittest.TestCase):
    """NotificationList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotificationList(self):
        """Test NotificationList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NotificationList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
